<?php /* @var $this Mage_Adminhtml_Block_Sales_Order_Create_Store_Select */ ?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"></div>
        <h4 class="fieldset-legend "><?php echo Mage::helper('orbaallegro')->__("Choose store");?></h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll store-scope">
            <div class="tree-store-scope">
                <?php foreach ($this->getWebsiteCollection() as $_website): ?>
                    <?php $showWebsite = false; ?>
                    <?php foreach ($this->getGroupCollection($_website) as $_group): ?>
                        <?php $showGroup = false; ?>
                        <?php foreach ($this->getStoreCollection($_group) as $_store): ?>
                            <?php if ($showWebsite == false): ?>
                                <?php $showWebsite = true; ?>
                                <h3><?php echo $this->escapeHtml($_website->getName()) ?></h3>
                            <?php endif; ?>
                            <?php if ($showGroup == false): ?>
                                <?php $showGroup = true; ?>
                                <h4 style="margin-left:12px;"><?php echo $this->escapeHtml($_group->getName()) ?></h4>
                            <?php endif; ?>
                            <span class="field-row" style="margin-left:28px;">
                                <?php $_login = $this->getLoginByStore($_store); ?>
                                <input type="radio" name="store_id" id="store_<?php echo $_store->getId() ?>" class="radio" <?php if($_login): ?>onclick="setLocation('<?php echo $this->getUrl('*/*/new', array('_current' => true, 'store'=>$_store->getId())); ?>')"<?php endif; ?>/>
                                <label for="store_<?php echo $_store->getId() ?>" class="inline">
                                    <?php echo $this->escapeHtml($_store->getName()) ?>
                                    <?php if($_login): ?>
                                        <?php if($_service = $this->getServiceByStore($_store)):?>
                                        <em>(<?php echo $this->getLoginByStore($_store);?> @ <?php echo $_service->getServiceName();?>)</em>
                                        <?php endif;?>
                                    <?php else:?>
                                        <em>(<?php echo $this->__('Not configured');?>)</em>
                                    <?php endif;?>
                                </label>
                            </span>
                        <?php endforeach; ?>
                        <?php if ($showGroup): ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
        </div>
     
    </div>
</div>