<div class="content-header">
   <h3><?php echo $this->getHeaderText() ?></h3>
   <p class="content-buttons form-buttons">
        <?php echo $this->getBackButtonHtml(); ?>
        <?php echo $this->getResetButtonHtml(); ?>
        <?php if ($this->getEditMode()): ?>
        <?php echo $this->getDeleteButtonHtml(); ?>
        <?php endif ?>
        <?php if ($this->getEditMode()): ?>
        <?php echo $this->getSaveAsButtonHtml(); ?>
        <?php endif ?>
        <?php echo $this->getSaveButtonHtml(); ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="template_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="no-display">
        <input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />
        <input type="hidden" id="save_as_flag" name="_save_as_flag" value="<?php echo $this->getSaveAsFlag() ?>" />
    </div>
    <?php echo $this->getForm() ?>
</form>
<script type="text/javascript">
//<![CDATA[
    var templateForm = new varienForm('template_edit_form');
    var templateControl = {
        init: function () {
            if ($('convert_button_back')) {
                $('convert_button_back').hide();
            }
        },
        save: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }
            templateForm.submit();
            return false;
        },
        saveAs: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }

            $('save_as_flag').value = '1';

            templateForm.submit();
            return false;
        },
        remove: function() {
            if(window.confirm("<?php echo Mage::helper('orbaallegro')->__('Are you sure that you want to delete this template?') ?>")) {
                window.location.href = '<?php echo $this->getDeleteUrl() ?>';
            }
        }
    };
    templateControl.init();
    
    function setSettings(urlTemplate, countryElement) {
        var template = new Template(urlTemplate, /(^|.|\r|\n)({{(\w+)}})/);
        setLocation(template.evaluate({country_code:$F(countryElement)}));
    }
    
</script>
