<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct()
?>
<?php if ($_additional = $this->getAdditionalData()): ?>
    <div class="oa-contant-subtitle oa-content-section">
        <h4 class="oa-text-accent"><?php echo Mage::helper("orbaallegro")->__("Product attributes"); ?></h4>
    </div>
    <div class="oa-contant-attributes oa-content-section">
        <table class="product-attributes">
            <tbody>
                <?php foreach ($_additional as $_data): ?>
                    <?php if(is_scalar($_data['value']) && !($_data['value']===null || $_data['value']==="" || $_data['value']===false)):?>
                    <tr>
                        <td class="label"><?php echo $this->htmlEscape($this->__($_data['label'])) ?></td>
                        <td class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                    </tr>
                    <?php endif;?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>