<ul class="oa-header-menu">
    <li><a href="{{var add_favourites_link}}" class="oa-text-accent"><strong>+</strong> Dodaj do ulubionych</a></li>
    <li><a href="{{var about_link}}" class="oa-text-regular">Strona &quot;o mnie&quot;</a></li>
    <li><a href="{{var auction_list_link}}" class="oa-text-regular">Nasze aukcje</a></li>
    <li><a href="{{var shop_link}}" class="oa-text-regular">Sklep Allegro</a></li>
    <li><a href="{{var comments_link}}" class="oa-text-regular">Komentarze</a></li>
</ul>