<div class="menu_do_left">
    <img src="http://deltaoptical.pl/allegro/menu_up.jpg" alt="">
    <div class="tekst" style="padding:20px; padding-top:10px;">
        <img src="http://deltaoptical.pl/allegro/n_kontakt.jpg"><BR>

        <b class="b">allegro@deltaoptical.pl</b>
        <BR><BR>
        tel.(25) 786-05-20<BR>
        fax: (25) 759-29-95 
        <BR><BR>
        Pracujemy pon-pt.w godz. 9-17. <BR>
        W tych godzinach odbieramy telefony
        i odpowiadamy na Państwa maile.

    </div>
    <img src="http://deltaoptical.pl/allegro/menu_down.jpg" alt="">
</div>

<div class="menu_do_left">
    <img src="http://deltaoptical.pl/allegro/menu_up.jpg" alt="">
    <div class="tekst" style="padding:20px; padding-top:10px;">
        <img src="http://deltaoptical.pl/allegro/n_dane_firmy.jpg"><BR>
        <b class="b">Delta Optical </b><BR>
        G. Matosek, H. Matosek Sp.j.<BR>
        Nowe Osiny, ul. Piękna 1<BR>
        05-300 Mińsk Mazowiecki<BR>
        REGON: 712386072<BR>
        NIP: 822-20-47-012<BR>
        KRS: 253028 <BR><BR>
        <b class="b">RACHUNEK BANKOWY</b><BR>
        18 1030 1582 0000 0008 1478 4002<BR>
        Bank: Bank Handlowy w Warszawie S.A.
    </div>
    <img src="http://deltaoptical.pl/allegro/menu_down.jpg" alt="">
</div>


<div class="menu_do_left">
    <img src="http://deltaoptical.pl/allegro/menu_up.jpg" alt="">
    <div class="tekst" style="padding:20px; padding-top:10px;">
        <img src="http://deltaoptical.pl/allegro/n_wysylka.jpg"><BR>
        Z ogromną starannością zabezpieczamy towar, aby nie uległ uszkodzeniu w czasie transportu.<BR>
        Wysyłka realizowana jest za pośrednictwem firmy kurierskiej GLS Poland.<BR><BR>
        Każdy nasz klient po dokonaniu zakupu otrzymuje maila z numerem przesyłki kurierskiej i może ją monitorować na stronie internetowej firmy GLS Poland.
        <BR><BR>
        <b class="b">Przy zakupach powyżej 200 zł koszt wysyłki kurierem<font color=red> GRATIS !!!</font></b>
        <BR><BR>
        Koszt wysyłki przy zakupach do 200 zł<BR>
        - wysyłka kurierska 15 zł<BR>
        - wysyłki kurierska pobraniowa 20 zł<br>
        - odbiór osobisty 0 zł
        <BR><BR>
        Tylko wybrane  przedmioty wysyłamy POCZTĄ POLSKĄ, jeśli istnieje taka możliwość podajemy koszt takiej wysyłki na aukcji.


    </div>
    <img src="http://deltaoptical.pl/allegro/menu_down.jpg" alt="">
</div>


<div class="menu_do_left">
    <img src="http://deltaoptical.pl/allegro/menu_up.jpg" alt="">
    <div class="tekst" style="padding:20px; padding-top:10px;">
        <img src="http://deltaoptical.pl/allegro/n_gwarancja_zwrotu.jpg"><BR>
        Klient może zrezygnować z towaru kupionego  na naszych  aukcjach w ciągu 10 dni od daty odebrania przesyłki.<BR> <BR>
        Każdy nabywca lunety bądź lornetki Titanium ma możliwość zwrotu produktu w ciągu 28 dni od daty zakupu. <BR><BR>
        Szczegółowe informacje zamieszczone są na stronie o mnie.

    </div>
    <img src="http://deltaoptical.pl/allegro/menu_down.jpg" alt="">
</div>


<div class="menu_do_left">
    <img src="http://deltaoptical.pl/allegro/menu_up.jpg" alt="">
    <div class="tekst" style="padding:20px; padding-top:10px;">
        <img src="http://deltaoptical.pl/allegro/n_profesjonalne_porady.jpg"><BR>
        W przypadku wątpliwości związanych z wyborem produktu, zakupem lub użytkowaniem, zachęcamy do kontaktu z naszymi  specjalistami. 
        <bR><BR><b class="b">tel.(25) 786-05-20 </b><BR>
        <a href="mailto:allegro@deltaoptical.pl">allegro@deltaoptical.pl</a>
    </div>
    <img src="http://deltaoptical.pl/allegro/menu_down.jpg" alt="">
</div>



<div class="menu_do_left">
    <img src="http://deltaoptical.pl/allegro/menu_up.jpg" alt="">
    <div class="tekst" style="padding:20px; padding-top:10px;">
        <img src="http://deltaoptical.pl/allegro/n_zakupy_ratalne.jpg"><BR>

        Prowadzimy sprzedaż ratalną za pośrednictwem Lukas Bank. <BR><BR>Istnieje możliwość uzyskania kredytu "na dowód" (bez zaświadczenia o dochodach) na zakupy do 5000zł. Spłatę kredytu na warunkach promocyjnych można rozłożyć na od 10 do 36 rat.
        Oprocentowanie wynosi ok. 1% miesięcznie.<BR><BR>

        Kontakt w sprawie kredytu<BR><b class="b">tel. (25) 786-05-22</b>
        <BR><a href="mailto:raty@deltaoptical.pl">raty@deltaoptical.pl</a>
    </div>
    <img src="http://deltaoptical.pl/allegro/menu_down.jpg" alt="">
</div>



<div class="menu_do_left">
    <img src="http://deltaoptical.pl/allegro/menu_up.jpg" alt="">
    <div class="tekst" style="padding:20px; padding-top:10px;">
        <img src="http://deltaoptical.pl/allegro/n_informacje.jpg"><BR>
        <b class="b">Wszystkie ceny sprzedaży są cenami brutto i zawierają podatek VAT.</b><BR><Br>
        Wszystkie towary sprzedawane przez firmę DELTAOPTICAL są nowe, fabrycznie zapakowane, objęte pisemną gwarancją (zwykle 2 letnią, sprzęt z linii Titanium posiada 5 letnią gwarancję).
        <BR><Br>
        Każdy kupujący otrzymuje dowód zakupu fakturę VAT lub paragon, gwarancję i instrukcję w języku polskim.
        <BR><Br>
        Posiadamy szybki i sprawny serwis wszystkich urządzeń dostępnych w naszej ofercie. Serwis zajmuje się obsługą napraw gwarancyjnych, jak również pogwarancyjnych.
        <BR><BR>
        Szczegółowe informacje dotyczące działania naszej firmy znajdziecie Państwo na STRONIE O MNIE.
    </div>
    <img src="http://deltaoptical.pl/allegro/menu_down.jpg" alt="">
</div>





<div class="menu_do_left">
    <img src="http://deltaoptical.pl/allegro/menu_up.jpg" alt="">
    <div class="tekst" style="padding:20px; padding-top:10px;">
        <img src="http://deltaoptical.pl/allegro/n_adresy.jpg"><BR>
        <b class="b"><font color="red">Zakupiony towar można odebrać w jednym z naszych czterech salonów sprzedaży.</font></b><BR><BR>
        Jeśli zdecydują się Państwo odebrać towar osobiście, bardzo prosimy o wcześniejszy kontakt telefoniczny lub mailowy, celem ustalenia terminu odbioru towaru.


        <BR><BR>
        W takiej sytuacji prosimy nie dokonywać wpłaty - płatność odbywa się na miejscu gotówką lub kartą płatniczą. 
        <BR><BR>
        <b class="b">CENTRALA  FIRMY - SKLEP FIRMOWY<BR>
            DELTA OPTICAL</b>
        <BR><BR>
        Nowe Osiny, ul. Piękna 1<BR>
        05-300 Mińsk Mazowiecki<BR>
        Czynne w godz. 8:30-17:00<BR><BR>
        tel.(25) 786-05-20<BR>
        fax: (25) 759-29-95
        <BR><BR><BR>
        <b class="b">SALON DELTA OPTICAL<BR>
            W WARSZAWIE</b>
        <BR><BR>
        Czynne pn.-pt. 10:00-19:00, sb. 10:00-14:00<BR>
        Warszawa, Al. Jana Pawła II 19<BR>
        Deloitte House (wejście z boku budynku). <BR><BR>
        Tel. (22) 624-08-04 
        <BR><BR><BR>
        <b class="b">SALON DELTA OPTICAL<BR>W KATOWICACH</b>
        <BR><BR>
        Czynne pn.-pt. 9:00-17:00, sob. 9:00-13:00<BR>
        Katowice, Uniwersytecka 13<BR>
        lokal na I piętrze Centrum Handlowego<BR><BR>
        tel. (32) 60-30-150
        <BR><BR><BR>
        <b class="b">SALON DELTA OPTICAL<BR>
            W GDAŃSKU</b>
        <BR><BR>
        Czynne pn.-pt. 10:00-18:00, sob. 10:00-14:00<BR>
        Gdańsk, Grunwaldzka 40/9 (wejście od ul. Do Studzienki)<BR><BR>
        tel. (25) 786-05-27
    </div>
    <img src="http://deltaoptical.pl/allegro/menu_down.jpg" alt="">
</div>


