<ul>
<li><a href="{{var about_link}}">O nas</a></li>
<li><img src="http://deltaoptical.pl/allegro/ciapek.png" alt="" /></li>
<li><a href="{{var auction_list_link}}">Nasze aukcje</a></li>
<li><img src="http://deltaoptical.pl/allegro/ciapek.png" alt="" /></li>
<li><a href="{{var comments_link}}">Komentarze</a></li>
{{if shop_link}}
<li><img src="http://deltaoptical.pl/allegro/ciapek.png" alt="" /></li>
<li><a href="{{var shop_link}}">Sklep Allegro</a></li>
{{/if}}
<li><img src="http://deltaoptical.pl/allegro/ciapek.png" alt="" /></li>
<li><a href="{{var user.getUserEmail()}}">Napisz do nas</a></li>
</ul>