<?php if(!$this->getIsFirstImportComplete() || !$this->getCanLogin()):?>
<?php $displayNote = ' display: none;';?>
<div style="margin-top: 10px;">
    <?php echo $this->
        getLayout()->
        createBlock("adminhtml/widget_button")->
        setLabel(Mage::helper("orbaallegro")->__(
            !$this->getIsFirstImportComplete() ? "Log in before next steps" : "Click to login")
        )->
        setId("orbaallegro_login_button")->
        setType("button")->
        toHtml();
    ?>
</div>
<?php else: ?>
<?php $displayNote ="";?>
<?php endif;?>
<p class="note" style="color: #090;<?php echo $displayNote?>" id="<?php echo $this->getElementId();?>_success">
    <span><?php echo Mage::helper("orbaallegro")->__("Login success");?></span>
</p>
<script type="text/javascript">  
    
    isFirstImportComplete = <?php echo (int)$this->getIsFirstImportComplete() ;?>;
    canLogin = <?php echo (int)$this->getCanLogin() ;?>;

    function handleOrbaallegroLoginButtonClick(event){
         var loginAndImportUrl = '<?php echo $this->getLoginAndImportUrl();?>',
             loginUrl = '<?php echo $this->getLoginUrl();?>',
             loginFiled = $('orbaallegro_config_user_login'),
             isSandBox = jQuery('#orbaallegro_config_use_sandbox'),
             loginFiledInherit = $('orbaallegro_config_user_login_inherit'),
             serviceField= $('orbaallegro_config_country_id'),
             serviceFieldInherit= $('orbaallegro_config_country_id_inherit'),
             apiKeyField = $('orbaallegro_config_api_key'),
             apiKeyFieldInherit = $('orbaallegro_config_api_key_inherit'),
             passwordField = $("<?php echo $this->getElementId();?>"),
             passwordFieldInherit = $("<?php echo $this->getElementId();?>_inherit"),
             data = {
                country_code: $F(serviceField),
                country_code_inherit: apiKeyFieldInherit ? $F(serviceFieldInherit) : 0,
                api_key: $F(apiKeyField),
                api_key_inherit: apiKeyFieldInherit ? $F(apiKeyFieldInherit) : 0,
                login: $F(loginFiled),
                login_inherit: loginFiledInherit ? $F(loginFiledInherit) : 0,
                password: $F(passwordField),
                password_inherit: passwordFieldInherit ? $F(passwordFieldInherit) : 0,
                is_sandbox: isSandBox.val()
             };

         if(!isFirstImportComplete){
            new Ajax.Request(loginAndImportUrl, {
               onSuccess: function(response) {
                   response = response.responseJSON;
                   if(response.result){
                       isFirstImportComplete = true;
                       canLogin = true;
                       orbaallegroReloadSelect(serviceField, response.content, $F(serviceField));
                       handleOrbaallegroServiceChanged();
                       $('orbaallegro_login_button').up('div').remove();
                       $('<?php echo $this->getElementId();?>_success').show();
                       switchSections(dependedSections , 1);
                   }else if(response.content){
                       alert(response.content);
                   }

               },
               parameters: Object.extend(<?php echo $this->getJsonParmas();?>, data)
             });
          }else if(!canLogin){
            new Ajax.Request(loginUrl, {
               onSuccess: function(response) {
                   response = response.responseJSON;
                   if(response.result){
                       canLogin = true;
                       orbaallegroReloadSelect(serviceField, response.content, $F(serviceField));
                       handleOrbaallegroServiceChanged();
                       $('orbaallegro_login_button').up('div').remove();
                       $('<?php echo $this->getElementId();?>_success').show();
                       switchSections(dependedSections , 1);
                   }else if(response.content){
                       alert(response.content);
                   }

               },
               parameters: Object.extend(<?php echo $this->getJsonParmas();?>, data)
             });
          }
          
    }
    
    document.observe("dom:loaded", function() {
        if(!isFirstImportComplete || !canLogin){
            switchSections(dependedSections , 0);
            $('orbaallegro_login_button').observe("click", handleOrbaallegroLoginButtonClick);
        }
    });
    
</script>
