<?php $_trans = $this->getModel(); ?>
<?php $_statArr = array(); ?>
<?php if((int)$_trans->getIsDeleted()):?>
    <?php $_statArr[] = Mage::helper("orbaallegro")->__("Expired");?>
<?php endif;?>
<?php if((int)$_trans->getIsIgnored()):?>
    <?php $_statArr[] = Mage::helper("orbaallegro")->__("Ignored");?>
<?php endif;?>
<div class="content-header">
    <h3>
        <?php echo $this->getHeaderText() ?>

        <?php if(count($_statArr)):?>
            <span class="orbaallegro-gray">(<?php echo join("/", $_statArr);?>)</span>
        <?php endif;?>
    </h3>
    <p class="content-buttons form-buttons">
        <?php echo $this->getBackButtonHtml(); ?>
        <?php echo $this->getRefreshButton(); ?>
        
        <?php if(!$this->getIsIgnored()):?>
            <?php if (!$this->getHasOrder()): ?>
                <?php echo $this->getCreateOrderButton(); ?>
                <?php echo $this->getIgnoreButton();?>
            <?php endif;?>
        <?php else:?>
            <?php echo $this->getUnIgnoreButton();?>
        <?php endif; ?>
    </p>
</div>

<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('orbaallegro')->__('General info'); ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Order') ?></label></td>
                    <td class="value">
                        <?php if ($_trans->getOrder()): ?>
                            <a href="<?php echo $this->getUrl("*/sales_order/view", array("order_id" => $_trans->getOrderId())); ?>">
                                <strong><?php echo $_trans->getOrder()->getIncrementId(); ?></strong>
                            </a>
                        <?php else: ?>
                            <?php if(!$this->getIsIgnored()):?>
                            <a href="<?php echo $this->getUrl("*/*/createOrder", array("transaction" => $_trans->getId())); ?>">
                                <?php echo Mage::helper('orbaallegro')->__('Place order') ?>
                            </a>
                            <?php else:?>
                                <?php echo Mage::helper('orbaallegro')->__('Please unignore transaction') ?>
                            <?php endif;?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Buyer login') ?></label></td>
                    <td class="value">
                        <strong>
                        <?php if($_contractor = $_trans->getContractor()):?>
                            <a href="<?php echo $this->getUrl("*/contractor/view", array("_current"=>true, "contractor"=>$_contractor->getId()));?>"><?php echo $_contractor->getLogin(); ?></a>
                        <?php else:?>
                            <?php echo $this->escapeHtml($_trans->getBuyerLogin());?>
                        <?php endif;?>
                        </strong>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Email'); ?></label></td>
                    <td class="value"><strong><?php echo $this->escapeHtml($_trans->getBuyerEmail()); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Transaction Allegro ID') ?></label></td>
                    <td class="value"><strong><?php echo $_trans->getAllegroTransactionId(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Transaction date') ?></label></td>
                    <td class="value"><strong><?php echo Mage::app()->getLocale()->date($_trans->getAllegroCreatedAt()) ?></strong></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('orbaallegro')->__('Prices and content'); ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Product count') ?></label></td>
                    <td class="value"><strong><?php echo $_trans->getItemCount(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Auction count') ?></label></td>
                    <td class="value"><strong><?php echo $_trans->getAuctionCount(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Subtotal') ?></label></td>
                    <td class="value"><strong><?php echo Mage::app()->getLocale()->currency($_trans->getCurrency())->toCurrency($_trans->getTransactionSubtotal());?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Shipping cost') ?></label></td>
                    <td class="value"><strong><?php echo Mage::app()->getLocale()->currency($_trans->getCurrency())->toCurrency($_trans->getTransactionCodAmount());?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Total') ?></label></td>
                    <td class="value"><strong><?php echo Mage::app()->getLocale()->currency($_trans->getCurrency())->toCurrency($_trans->getTransactionTotal());?></strong></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class="clear"></div>

<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('orbaallegro')->__('Payment'); ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php if ($_payment = $_trans->getPayment()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Payment method') ?></label></td>
                        <td class="value">
                            <strong>
                                <?php echo $this->escapeHtml($_payment->getName()); ?>
                            </strong>
                            <?php if ($_payment->getIsPayu()): ?>
                                (<?php echo Mage::helper('orbaallegro')->__('Payu.pl') ?>)
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php if ($_payment->getIsPayu() && $_trans->getAllegroPayuStatus()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('PayU status') ?></label></td>
                        <td class="value">
                            <strong>
                                <?php echo $this->escapeHtml($_trans->getAllegroPayuStatus()); ?>
                            </strong>
                            <?php if($_trans->getAllegroPayuTransactionId()):?>
                            (<?php echo Mage::helper('orbaallegro')->__('No.') ?> <?php echo $_trans->getAllegroPayuTransactionId();?>)
                            <?php endif;?>
                        </td>
                    </tr>
                    <?php endif;?>
                    <?php if($_trans->isPaymentMapped() && ($_paymentMethod=$_trans->getPaymentMethod())):?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Local') ?></label></td>
                        <td class="value"><strong><?php echo $_paymentMethod->getTitle();?></strong>
                    </tr>
                    <?php endif;?>
                <?php endif; ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Want invoice') ?></label></td>
                    <td class="value">
                        <strong>
                            <?php if ($_trans->getBuyerInvoice()): ?>
                                <?php echo Mage::helper('orbaallegro')->__('Yes') ?>
                            <?php else: ?>
                                <?php echo Mage::helper('orbaallegro')->__('No') ?>
                            <?php endif; ?>
                        </strong>
                    </td>
                </tr>

                <?php if ($_billing = $_trans->getAddress(Orba_Allegro_Model_Transaction_Address::TYPE_BILLING)): ?>
                    <?php if ($_billing->getVatid()): ?>
                        <tr>
                            <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('NIP') ?></label></td>
                            <td class="value"><strong><?php echo $this->escapeHtml($_billing->getVatid()); ?></strong></td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Billing address') ?></label></td>
                        <td class="value">
                            <strong>
                                <?php if ($_billing->getCompany()): ?>
                                    <?php echo $this->escapeHtml($_billing->getCompany()); ?>
                                    <br/>
                                <?php endif; ?>
                                <?php if($_billing->getFullname()):?>
                                    <?php echo $this->escapeHtml($_billing->getFullname()); ?>
                                    <br/>
                                <?php endif;?>
                                <?php echo $this->escapeHtml($_billing->getStreet()); ?>
                                <br/>
                                <?php echo $this->escapeHtml($_billing->getPostcode()); ?>
                                <?php echo $this->escapeHtml($_billing->getCity()); ?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Country') ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($this->getCountryLabel($_billing->getCountryCode())); ?></strong></td>
                    </tr>
                    <?php if ($_billing->getPhone()): ?>
                        <tr>
                            <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Phone') ?></label></td>
                            <td class="value"><strong><?php echo $this->escapeHtml($_billing->getPhone()); ?></strong></td>
                        </tr>
                    <?php endif; ?>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>

<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('orbaallegro')->__('Shipping'); ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php if ($_shipment = $_trans->getShipment()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Shipping method') ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($_shipment->getName()); ?></strong></td>
                    </tr>
                    <?php if(($_currierMethod = $_trans->getCarrierMethod()) && $_trans->getIsCarrierMapped()):?>
                        <tr>
                            <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Local') ?></label></td>
                            <td class="value">
                                <strong><?php echo $_currierMethod->getTitle();?></strong>
                                (<?php echo $_currierMethod->getCarrierName();?>)
                            </td>
                        </tr>
                    <?php endif;?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Shipping cost') ?></label></td>
                        <td class="value"><strong><?php echo Mage::helper('core')->currency($_trans->getTransactionCodAmount(), $_trans->getCurrency()) ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Shipping type') ?></label></td>
                        <td class="value">
                            <strong>
                                <?php if($_shipment->getType()==$_shipment::TYPE_PREPAY):?>
                                    <?php echo Mage::helper('orbaallegro')->__('Prepay') ?>
                                <?php else:?>
                                    <?php echo Mage::helper('orbaallegro')->__('Cash on delivery') ?>
                                <?php endif;?>
                            </strong>
                        </td>
                    </tr>
                    <?php /* Should use pickpoint ? */ ?>
                    <?php if ($_shipment->getIsPickpoint()): ?>
                        <?php /* Freezed pickpoint address ? */ ?>
                        <?php if ($_pickpoint = $_trans->getAddress(Orba_Allegro_Model_Transaction_Address::TYPE_PICKPOINT)): ?>
                            <?php $_pickpointModel = $_pickpoint->getPickpoint(); ?>
                            <?php /* Actual pickpoint code ? */ ?>
                            <?php if ($_pickpointModel->getId()): ?>
                                <tr>
                                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Pickpoint code') ?></label></td>
                                    <td class="value"><strong><?php echo $this->escapeHtml($_pickpointModel->getPickpointCode()); ?></strong></td>
                                    </td>
                                </tr>
                            <?php endif; ?>
                            <tr>
                                <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Pickpoint address') ?></label></td>
                                <td class="value">
                                    <strong>
                                        <?php echo $this->escapeHtml($_pickpoint->getFullname()); ?>
                                        <br/>
                                        <?php echo $this->escapeHtml($_pickpoint->getStreet()); ?>
                                        <br/>
                                        <?php echo $this->escapeHtml($_pickpoint->getPostcode()); ?>
                                        <?php echo $this->escapeHtml($_pickpoint->getCity()); ?>
                                    </strong>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Country') ?></label></td>
                                <td class="value"><strong><?php echo $this->escapeHtml($this->getCountryLabel($_pickpoint->getCountryCode())); ?></strong></td>
                            </tr>
                            <?php if ($_pickpoint->getPhone()): ?>
                                <tr>
                                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Phone') ?></label></td>
                                    <td class="value"><strong><?php echo $this->escapeHtml($_pickpoint->getPhone()); ?></strong></td>
                                </tr>
                            <?php endif; ?>
                        <?php else:?>
                            <tr>
                                <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Pickpoint') ?></label></td>
                                <td class="value"><strong><?php echo Mage::helper('orbaallegro')->__('No data') ?></strong></td>
                            </tr>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if ($_shipping = $_trans->getAddress(Orba_Allegro_Model_Transaction_Address::TYPE_SHIPPING)): ?>
                            <tr>
                                <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Shipping address') ?></label></td>
                                <td class="value">
                                    <strong>
                                        <?php if ($_shipping->getCompany()): ?>
                                            <?php echo $this->escapeHtml($_shipping->getCompany()); ?>
                                            <br/>
                                        <?php endif; ?>
                                        <?php if($_shipping->getFullname()):?>
                                            <?php echo $this->escapeHtml($_shipping->getFullname()); ?>
                                            <br/>
                                        <?php endif;?>
                                        <?php echo $this->escapeHtml($_shipping->getStreet()); ?>
                                        <br/>
                                        <?php echo $this->escapeHtml($_shipping->getPostcode()); ?>
                                        <?php echo $this->escapeHtml($_shipping->getCity()); ?>
                                    </strong>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Country') ?></label></td>
                                <td class="value"><strong><?php echo $this->escapeHtml($this->getCountryLabel($_shipping->getCountryCode())); ?></strong></td>
                            </tr>
                            <?php if ($_shipping->getPhone()): ?>
                                <tr>
                                    <td class="label"><label><?php echo Mage::helper('orbaallegro')->__('Phone') ?></label></td>
                                    <td class="value"><strong><?php echo $this->escapeHtml($_shipping->getPhone()); ?></strong></td>
                                </tr>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>
<div class="clear"></div>
   
<?php if ($_trans->getBuyerMessage()): ?>
 

    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('orbaallegro')->__('Buyer message'); ?></h4>
        </div>
        <div class="fieldset">
            <p><?php echo $this->escapeHtml($_trans->getBuyerMessage()); ?></p>
        </div>
    </div>
<?php endif; ?>


<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo Mage::helper('orbaallegro')->__('Transaction items'); ?></h4>
    </div>
    <div class="fieldset">
        <?php echo $this->getChildHtml("grid"); ?>
    </div>
</div>